import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  searchContainer: {
    padding: 10,
    backgroundColor: '#f8f8f8',
  },
  searchInput: {
    height: 45,
    borderWidth: 1,
    borderColor: '#ccc',
    paddingHorizontal: 15,
    borderRadius: 8,
    backgroundColor: '#fff',
    fontSize: 16,
  },
  itemContainer: {
    padding: 20,
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    alignItems: "center",
    justifyContent: "center",
  },
  headerImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
  },
  title: {
    fontSize: 18,
    textAlign: "center",
  },
  titleBold: {
    fontWeight: 'bold',
  },
  swipeAction: {
    backgroundColor: '#3498db',
    justifyContent: 'center',
    paddingHorizontal: 20,
    height: '100%',
  },
  swipeText: {
    color: 'white',
    fontWeight: 'bold',
  },
  offlineContainer: {
    backgroundColor: '#b00020',
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    zIndex: 1000,
  },
  offlineText: { 
    color: '#fff', 
    fontSize: 12,
    fontWeight: 'bold',
  },
  detailContainer: {
    flex: 1,
    backgroundColor: '#f4f4f4',
  },
  detailHeader: {
    padding: 40,
    backgroundColor: '#000000',
    alignItems: 'center',
  },
  detailName: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
  },
  detailCard: {
    margin: 20,
    padding: 15,
    backgroundColor: '#fff',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  detailLabel: {
    fontWeight: '600',
    color: '#7f8c8d',
    fontSize: 16,
  },
  detailValue: {
    color: '#2c3e50',
    fontSize: 16,
    textTransform: 'capitalize',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#34495e',
    margin: 10,
    borderRadius: 8,
    alignSelf: 'flex-start',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  backButtonText: {
    color: '#ecf0f1',
    fontWeight: 'bold',
    fontSize: 14,
  },
});